### ISSUE TITLE
啥时候有时间能更新一下节目源

### ISSUE THREAD

**Issue by channingbox** [Wyf841015/JLLTIPTV#10]
看看是不是有些节目有变化

**Comment by Wyf841015** [comment]
等十月下旬吧，很久没开过机顶盒了，最近比较忙



---原始邮件---
发件人: "channingbox"<notifications@github.com&gt;
发送时间: 2020年10月9日(周五) 晚上7:31
收件人: "Wyf841015/JLLTIPTV"<JLLTIPTV@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Wyf841015/JLLTIPTV] 啥时候有时间能更新一下节目源 (#10)




 
看看是不是有些节目有变化

**Comment by Wyf841015** [comment]
已更新



---原始邮件---
发件人: "channingbox"<notifications@github.com&gt;
发送时间: 2020年10月9日(周五) 晚上7:31
收件人: "Wyf841015/JLLTIPTV"<JLLTIPTV@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Wyf841015/JLLTIPTV] 啥时候有时间能更新一下节目源 (#10)




 
看看是不是有些节目有变化

**Comment by aaaisan** [comment]
thx~
