### ISSUE TITLE
你家是白城的吗，我看那个ip是白城的

### ISSUE THREAD

**Issue by channingbox** [Wyf841015/JLLTIPTV#2]
吉林联通的iptv地址是有多个吗，长春联通又会另外的吗

**Comment by channingbox** [comment]
手机端安卓 MX Player，坐标长春联通，可以播放你放出的节目列表，测试了吉林卫视标清和央视高清。

**Comment by channingbox** [comment]
我手机是分辨率是1080p的，看高清节目很爽，标清的还好，吉林有线央视都换成高清的了，联通有些却还是标清。

**Comment by Wyf841015** [comment]
不是，长春的


 
---原始邮件---
发件人: "channingbox"<notifications@github.com>
发送时间: 2019年6月16日(星期日) 下午3:51
收件人: "Wyf841015/JLLTIPTV"<JLLTIPTV@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Wyf841015/JLLTIPTV] 你家是白城的吗，我看那个ip是白城的 (#2)



吉林联通的iptv地址是有多个吗，长春联通又会另外的吗

**Comment by channingbox** [comment]
你家安装的联通宽带，华为盒子是联通送的看iptv的？

**Comment by Wyf841015** [comment]
是的，就是送的


 
---原始邮件---
发件人: "channingbox"<notifications@github.com>
发送时间: 2019年6月16日(星期日) 下午4:54
收件人: "Wyf841015/JLLTIPTV"<JLLTIPTV@noreply.github.com>;
抄送: "Comment"<comment@noreply.github.com>;"Wyf841015"<64652178@qq.com>;
主题: Re: [Wyf841015/JLLTIPTV] 你家是白城的吗，我看那个ip是白城的 (#2)



你家安装的联通宽带，华为盒子是联通送的看iptv的？
