### ISSUE TITLE
有些播放源需要更新了

### ISSUE THREAD

**Issue by channingbox** [Wyf841015/JLLTIPTV#3]
如题

**Comment by Wyf841015** [comment]
最近没有时间弄，有时间更新一下



---原始邮件---
发件人: "channingbox"<notifications@github.com>
发送时间: 2019年7月22日(星期一) 中午1:12
收件人: "Wyf841015/JLLTIPTV"<JLLTIPTV@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Wyf841015/JLLTIPTV] 有些播放源需要更新了 (#3)



如题

**Comment by channingbox** [comment]
我觉得高清源比较有价值，可以高清的放一起或者干脆不要低清的垃圾节目了

**Comment by channingbox** [comment]
中央7现在分成两个频道了
