### ISSUE TITLE
昨天开始好像全部失效了

### ISSUE THREAD

**Issue by channingbox** [Wyf841015/JLLTIPTV#7]
求测试

**Comment by Wyf841015** [comment]
有时间测试下



---原始邮件---
发件人: "channingbox"<notifications@github.com&gt;
发送时间: 2020年1月1日(周三) 凌晨5:59
收件人: "Wyf841015/JLLTIPTV"<JLLTIPTV@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Wyf841015/JLLTIPTV] 昨天开始好像全部失效了 (#7)



求测试

**Comment by Wyf841015** [comment]
已更新



---原始邮件---
发件人: "channingbox"<notifications@github.com&gt;
发送时间: 2020年1月1日(周三) 凌晨5:59
收件人: "Wyf841015/JLLTIPTV"<JLLTIPTV@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Wyf841015/JLLTIPTV] 昨天开始好像全部失效了 (#7)



求测试

**Comment by channingbox** [comment]
换成了长春的ip，又都可用了。长春联通啥时候央视一组能全换成高清。
